---
title: "BIOS 611 Final Project"
author: "Camille Liu"
date: "10/28/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load packages
pkgs <- list('tidyverse')
lapply(pkgs, require, character.only = T)
#load_all('./final')

# run_from_scratch = FALSE uses saved model objects
# set to TRUE if want to run from scratch
run_from_scratch = FALSE

# read data
dat_full <- read_delim("bank-full.csv", delim=';')
```

(steps...)


```{r DataPreprocessing, warning=FALSE}
# combine the labels
q1 <- c('mar','feb','jan')
q2 <- c('apr','may','jun')
q3 <- c('jul','aug','sep')
q4 <- c('nov','oct','dec')

# #collape month into quarters
# dat_full$month<-recode(dat_full$month,
#                        "q1='q1'; q2='q2'; q3 = 'q3'; q4 = 'q4'")

# drop pdays and duration
dat = dat_full %>% select(-pdays, -duration)

# analysis dataset
set.seed(100)
dat.working <- dat %>% 
  mutate_if(is.character, as.factor) %>% # convert character to factor
  slice_sample(prop = 0.2) # select subset
```

```{r SelectTrain/test}

# put continuous vars on same scale as indicators
# put here b/c want summary table/figures to show on raw scale
scale2sd <- function(x) {
  (x - mean(x) )/ (2*sd(x))
}

dat.working = dat.working %>%
  mutate(age = scale2sd(age),
         campaign = scale2sd(campaign),
         balance = scale2sd(balance),
         previous = scale2sd(previous))

# select training and testing data
set.seed(100)
# y <- dat.working$y
# index <- createDataPartition(
#   y,
#   times = 1,
#   p = 0.8,
#   list = F,
#   groups = min(5, length(y))
# )
# dat_train <- dat.working[index,]
# dat_test <- dat.working[-index,]

```